// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppProvider: typeof import('./../src/components/Application/AppProvider.vue')['default']
    BasicLayout: typeof import('./../src/layouts/components/BasicLayout/BasicLayout.vue')['default']
    ChangeTheme: typeof import('./../src/layouts/components/Header/components/ChangeTheme.vue')['default']
    Dialog: typeof import('./../src/views/home/components/dialog.vue')['default']
    Header: typeof import('./../src/layouts/components/Header/Header.vue')['default']
    Menus: typeof import('./../src/layouts/components/Menus/Menus.vue')['default']
  }
}

export { }
