// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    Dialog: typeof import('./views/home/components/dialog.vue')['default']
    ScrollList: typeof import('./components/ScrollList.vue')['default']
  }
}

export { }
